CBL-3663: Fix LiteCore assertion failure
couchbasedeps/sockpp pull request #11
Opened 2022-10-07 13:36 UTC by callumbirks

Change return value of MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY to a valid POSIX error (ECONNRESET) rather than 0

2022-10-07 16:48 UTC, pasin requested changes
The PR also pulls a lot of stuff from already merged code? Can you check if you create a PR for the right branch?

2022-10-07 16:50 UTC, callumbirks commented
@pasin Apologies, had selected master branch to merge into rather than couchbase-master

2022-10-08 01:11 UTC, pasin approved these changes

2022-10-08 01:12 UTC, pasin approved these changes

2022-10-08 01:12 UTC, pasin commented on src/mbedtls_context.cpp
> +        //  failure in LiteCore TCPSocket::checkStreamError()
Minor : there is a space in front of `failure`.

2022-10-10 08:59 UTC, merged